### PR TITLE
Add RAW video files functionality

### PR DESCRIPTION
**Pull request by pifry**
Hello Raivo,
It's me again, back with something more than just quick doc fix ;) I'm using your Dataset to work with video data, but in my case I have datasets consisting of RAW video data (not split into frames). I added functionality to deal with such files. I implemented only [nv12 planar format](https://www.fourcc.org/pixel-format/yuv-nv12/) for now but, i think, the way it's implemented makes it extendable. What do you make of it? Will you merge?
Also I added some unit tests to pin down current and new functionality to assure it's backwards compatibility.
P.

### CODE REVIEW

**Comment by RaivoKoot** [comment]
Hey again! Wow, very cool to see that you are extending the project. Thanks for the effort (including testing and stuff)! I will need some time to review your code and make a decision.

The project's main aim is to be as **simple** and therefore **accessible** as possible. Because many deep learning tools that help you load video datasets have a high entry barrier because they are complicated, I want new users of this repository to only see the **minimum** amount of code necessary for basic RGB usage. So overall, I am worried that adding more advanced functionality will scare new people off again. I will think about whether I prefer 1) adding your functionality straight into the existing code as you have prepared in this PR, or 2) making it more separate so that the additional functionality is available, but leaves the minimal original code standalone.

**Comment by pifry** [comment]
Hello Raivo,
I understand your point and because of this i write my code in such a way
that the user do not need to do anything extra in simple cases.
In the beginning i implemented this functionality as a subclass of
VideoFrameDataset. It worked but the code wasn't very clean. Entire image
load method has to be overload. And there is of course completely new
responsibility of VideoRecord.
There are many datasets all over the internet provided in raw format. Users
of those could benefit from your great work. I'm waiting for your review
and sugestions thou.
Yours sincerely
P.

pon., 17 maj 2021, 17:40 użytkownik Raivo Eli Koot ***@***.***>
napisał:

**Comment by RaivoKoot** [comment]
Thanks for the explanation. I currently have a conference deadline in ~10 days and will likely have to postpone reviewing the code until after. Curious to see what you have come up with though!

On a side note: Currently the repo makes the users responsible to get the annotation files of their dataset into the format that VideoFrameDataset needs. It also requires users to put their video dataset into RGB frames on disk. I am thinking of supplying some pre-made annotation files for popular datasets (EPIC-KITCHENS-100 and Something-Something-V2), including a script that converts video files into RGB folders.

This would help people get started even faster, who are aiming to use these datasets.

**Comment by RaivoKoot** [comment]
Unfortunately, I won't merge your PR, because I want to preserve the simplicity and understandability of the code.

**Pull request closed without merging**
